import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

# Set up the page layout
st.set_page_config(page_title="Quant Prediction Dashboard", layout="wide")

st.title("📈 Stock Return Prediction Dashboard")
st.markdown("---")

# Load the simulation results
@st.cache_data
def load_data():
    df = pd.read_csv("simulation_results.csv")
    # Clean up index column if necessary
    if "Unnamed: 0" in df.columns:
        df.rename(columns={"Unnamed: 0": "Date"}, inplace=True)
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    return df

try:
    df = load_data()

    # --- SIDEBAR: FINANCIAL PERFORMANCE METRICS ---
    st.sidebar.header("📊 Strategy Performance")
    
    # Calculate some quick metrics on the fly from your sheet
    final_strat = df['Cumulative_Strategy_Return'].iloc[-1] * 100
    final_bh = df['Cumulative_Buy_Hold_Return'].iloc[-1] * 100
    outperformance = final_strat - final_bh

    st.sidebar.metric(label="AI Strategy Total Return", value=f"{final_strat:.2f}%")
    st.sidebar.metric(label="Buy & Hold Benchmark", value=f"{final_bh:.2f}%")
    st.sidebar.metric(label="Alpha (Outperformance)", value=f"{outperformance:+.2f}%", delta=f"{outperformance:.2f}%")

    # --- MAIN PAGE LAYOUT ---
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("Simulated Equity Curve")
        # Build an interactive Plotly graph for the returns
        fig_equity = go.Figure()
        fig_equity.add_trace(go.Scatter(x=df.index, y=df['Cumulative_Strategy_Return'], mode='lines', name='AI Strategy', line=dict(color='#00CC96', width=2)))
        fig_equity.add_trace(go.Scatter(x=df.index, y=df['Cumulative_Buy_Hold_Return'], mode='lines', name='Buy & Hold Benchmark', line=dict(color='#636EFA', dash='dash')))
        
        fig_equity.update_layout(
            template="plotly_dark",
            xaxis_title="Date",
            yaxis_title="Cumulative Return",
            margin=dict(l=20, r=20, t=20, b=20),
            hovermode="x unified"
        )
        st.plotly_chart(fig_equity, use_container_width=True)

    with col2:
        st.subheader("Model Confidence")
        st.write("Distribution of the prediction probabilities generated by the Random Forest model.")
        
        # Historical probability distribution chart
        fig_hist = px.histogram(df, x="Prediction_Probability", nbins=30, title="Prediction Probabilities", color_discrete_sequence=['#AB63FA'])
        fig_hist.update_layout(template="plotly_dark", margin=dict(l=20, r=20, t=30, b=20))
        st.plotly_chart(fig_hist, use_container_width=True)

    # --- RECENT PREDICTIONS TABLE ---
    st.subheader("📋 Recent Trading Signals")
    # Grab the last 10 trading days to show the recent signals
    recent_df = df[['Actual_Target', 'Predicted_Target', 'Prediction_Probability']].tail(10).copy()
    recent_df['Signal'] = recent_df['Predicted_Target'].apply(lambda x: "🚀 BUY / LONG" if x == 1 else "🛑 HOLD / CASH")
    
    # Reverse order so newest is at the top
    st.dataframe(recent_df.iloc[::-1], use_container_width=True)

except Exception as e:
    st.error(f"Error loading dashboard elements: {e}")
    st.write("Please check that your simulation_results.csv contains the correct backtest data columns.")
